
spring:
  profiles:
    active: youngwonhe2



---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/spring_batch?useUnicode=true&characterEncoding=utf8
      username: spring_batch
      password: spcplus001!
      driver-class-name: org.mariadb.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: youngwonhe2
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://nodejs-013.cafe24.com:3306/youngwonhe2?useUnicode=true&characterEncoding=utf8
      username: youngwonhe2
      password: luna12!!
      driver-class-name: org.mariadb.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: true
  sql:
    init:
      mode: always
      data-locations: classpath:data-younwonhe2.sql